# import libraries

In [ ]:
import os
import time
from pathlib import Path

import pandas as pd  
import time 
from tqdm import tqdm 
from dotenv import load_dotenv, find_dotenv

# Directories

In [9]:
DATA_DIR = Path("../data")
LATEST_MOVIES_PATH = DATA_DIR / 'latest_movies' / "tmdb_latest_movies.csv"
TMDB_DIR = DATA_DIR / 'tmdb'
MOVIELENS_DIR = DATA_DIR / 'movielens'
print(f"DATA_DIR: {DATA_DIR.resolve()}")

DATA_DIR: C:\52300070_TMTHUYEN\LEARN_MORE\Apps\dacntt-movie-recommendation\ai-service\data

# Load data

## MovieLens dataset

In [19]:
movielens_df = {
    "ratings": pd.read_csv(MOVIELENS_DIR / "ratings.csv"),
    "tags": pd.read_csv(MOVIELENS_DIR / "tags.csv"),
    "links": pd.read_csv(MOVIELENS_DIR / "links.csv"),
    "movies": pd.read_csv(MOVIELENS_DIR / "movies.csv"),
    "genome_scores": pd.read_csv(MOVIELENS_DIR / "genome_scores.csv"),
    "genome_tags": pd.read_csv(MOVIELENS_DIR / "genome_tags.csv")
}

print('Số phim: ', movielens_df['movies'].shape[0]) 
print('Số người dùng: ', movielens_df['ratings']['userId'].nunique())
print('Số lượt đánh giá: ', movielens_df['ratings'].shape[0])

Số phim:  58098
Số người dùng:  283228
Số lượt đánh giá:  27753444

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [22]:

display(movielens_df['movies'].head(5))
display(movielens_df['ratings'].head(5))
display(movielens_df['tags'].head(5))
display(movielens_df['links'].head(5))
display(movielens_df['genome_scores'].head(5))
display(movielens_df['genome_tags'].head(5))

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

   userId  movieId  rating   timestamp
0       1      307     3.5  1256677221
1       1      481     3.5  1256677456
2       1     1091     1.5  1256677471
3       1     1257     4.5  1256677460
4       1     1449     4.5  1256677264

   userId  movieId           tag   timestamp
0      14      110          epic  1443148538
1      14      110      Medieval  1443148532
2      14      260        sci-fi  1442169410
3      14      260  space action  1442169421
4      14      318  imdb top 250  1442615195

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

   movieId  tagId  relevance
0        1      1    0.02900
1        1      2    0.02375
2        1      3    0.05425
3        1      4    0.06875
4        1      5    0.16000

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

## TMDB movies info

In [35]:
# tmdb_df1 = pd.read_csv(TMDB_DIR / 'movies_metadata_0-10000_1995-01-01.csv')
# tmdb_df2 = pd.read_csv(TMDB_DIR / 'movies_metadata_11000-20000_1995-01-01.csv')

# # merge
# tmdb_df = pd.concat([tmdb_df1, tmdb_df2], ignore_index=True)
# tmdb_df.to_csv(TMDB_DIR / 'movies_metadata_merged.csv', index=False, encoding='utf-8-sig')

# tmdb_df = pd.read_csv(TMDB_DIR / 'movies_metadata_merged_2000-01-01.csv', encoding='utf-8-sig')
tmdb_df = pd.read_csv(TMDB_DIR / 'movies_data_fully_translated.csv', encoding='utf-8-sig')

tmdb_df.info()

display(tmdb_df.head(5))
display(tmdb_df[tmdb_df['release_date'] > '2000-01-01'].count())
tmdb_df[tmdb_df['release_date'] > '2000-01-01'].to_csv(TMDB_DIR / 'movies_metadata_merged_2000-01-01.csv', index=False, encoding='utf-8-sig')

<class 'pandas.DataFrame'>
RangeIndex: 9811 entries, 0 to 9810
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   tmdbId                 9811 non-null   float64
 1   title_vi               9811 non-null   str
 2   overview_vi            9811 non-null   str
 3   genres                 9811 non-null   str
 4   release_date           9811 non-null   str
 5   poster_path            9800 non-null   str
 6   adult                  9811 non-null   bool
 7   backdrop_path          9558 non-null   str
 8   belongs_to_collection  1616 non-null   str
 9   budget                 9811 non-null   int64
 10  homepage               1 non-null      str
 11  id                     9811 non-null   int64
 12  imdb_id                9810 non-null   str
 13  origin_country         9811 non-null   str
 14  original_language      9811 non-null   str
 15  original_title         9811 non-null   str
 16  overview               9810 non-null   str
 17  popularity             9811 non-null   float64
 18  production_companies   9811 non-null   str
 19  production_countries   9811 non-null   str
 20  revenue                9811 non-null   int64
 21  runtime                9811 non-null   int64
 22  softcore               9811 non-null   bool
 23  spoken_languages       9811 non-null   str
 24  status                 9811 non-null   str
 25  tagline                593 non-null    str
 26  title                  9811 non-null   str
 27  video                  9811 non-null   bool
 28  vote_average           9811 non-null   float64
 29  vote_count             9811 non-null   int64
 30  movieId                9811 non-null   float64
 31  is_ai_translated       9811 non-null   bool
dtypes: bool(4), float64(4), int64(5), str(19)
memory usage: 16.5 MB

,tmdbId,title_vi,overview_vi,genres,release_date,poster_path,adult,backdrop_path,belongs_to_collection,budget,...,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count,movieId,is_ai_translated
0,131232.0,Due amici,"Bạn bè hai tuổi, Nunzio và Pino, có chung một ...","[{'id': 18, 'name': 'Phim Chính Kịch'}]",2002-03-20,/ja7a0XvTUIQ6w1YdvbtytdC1lTF.jpg,False,/r1boovecPQAZo6vQBLZ4NVeRT2g.jpg,NaN,0,...,False,"[{'english_name': 'Italian', 'iso_639_1': 'it'...",Released,NaN,Due amici,False,5.400,7,723.0,True
1,79782.0,Wenecja,Một câu chuyện sắp tới kể về một cậu bé tên là...,"[{'id': 18, 'name': 'Phim Chính Kịch'}, {'id':...",2010-06-11,/jk8PwaZ14Duxy8hmLbYLFcYTUP9.jpg,False,/8vrmhLhPucmEOJr6EDxhxzVDMXi.jpg,NaN,1783810,...,False,"[{'english_name': 'Czech', 'iso_639_1': 'cs', ...",Released,NaN,Wenecja,False,7.139,18,895.0,True
2,141210.0,The Sleepover,"Thị trấn Derry có một bí mật, nhưng không ai n...","[{'id': 35, 'name': 'Phim Hài'}, {'id': 27, 'n...",2012-10-12,/tdaZD1Db9CXu96oLdAHElJsBPfb.jpg,False,NaN,NaN,0,...,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,The Sleepover,False,6.500,11,1115.0,True
3,143750.0,The Farmer's Wife,Khi môi trường của cô bị xâm chiếm bởi người n...,"[{'id': 18, 'name': 'Phim Chính Kịch'}]",2012-06-20,NaN,False,NaN,NaN,0,...,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,The Farmer's Wife,False,10.000,1,2223.0,True
4,84198.0,A Place at the Table,"Sử dụng những câu chuyện cá nhân, những tài li...","[{'id': 99, 'name': 'Phim Tài Liệu'}]",2012-03-22,/ptli8HtDrapZdVdBnYSN8zxJtw0.jpg,False,/hdFefzO4RPq4txKEbFU7EulePsS.jpg,NaN,0,...,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,NaN,A Place at the Table,False,6.593,27,2679.0,True

tmdbId                   9811
title_vi                 9811
overview_vi              9811
genres                   9811
release_date             9811
poster_path              9800
adult                    9811
backdrop_path            9558
belongs_to_collection    1616
budget                   9811
homepage                    1
id                       9811
imdb_id                  9810
origin_country           9811
original_language        9811
original_title           9811
overview                 9810
popularity               9811
production_companies     9811
production_countries     9811
revenue                  9811
runtime                  9811
softcore                 9811
spoken_languages         9811
status                   9811
tagline                   593
title                    9811
video                    9811
vote_average             9811
vote_count               9811
movieId                  9811
is_ai_translated         9811
dtype: int64

## Latest TMDB movies

In [26]:
latest_movies_df = pd.read_csv(LATEST_MOVIES_PATH)

display(latest_movies_df.info())

display(latest_movies_df.count())

display(latest_movies_df.sort_values('release_date', ascending=True).head(5))

<class 'pandas.DataFrame'>
RangeIndex: 5075 entries, 0 to 5074
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   tmdb_id            5075 non-null   int64
 1   title_vi           5075 non-null   str
 2   overview_vi        4357 non-null   str
 3   adult              5075 non-null   bool
 4   backdrop_path      2777 non-null   str
 5   genre_ids          5075 non-null   str
 6   id                 5075 non-null   int64
 7   title              5075 non-null   str
 8   original_language  5075 non-null   str
 9   original_title     5075 non-null   str
 10  overview           4357 non-null   str
 11  popularity         5075 non-null   float64
 12  poster_path        4330 non-null   str
 13  release_date       5070 non-null   str
 14  softcore           5075 non-null   bool
 15  video              5075 non-null   bool
 16  vote_average       5075 non-null   float64
 17  vote_count         5075 non-null   int64
dtypes: bool(3), float64(2), int64(3), str(10)
memory usage: 3.3 MB

None

tmdb_id              5075
title_vi             5075
overview_vi          4357
adult                5075
backdrop_path        2777
genre_ids            5075
id                   5075
title                5075
original_language    5075
original_title       5075
overview             4357
popularity           5075
poster_path          4330
release_date         5070
softcore             5075
video                5075
vote_average         5075
vote_count           5075
dtype: int64

,tmdb_id,title_vi,overview_vi,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
880,75571,Our War Game,Spring break turns into a summer war when the ...,False,/m3g7v9ChQE2keBS4RMUxfmWn1xy.jpg,"[12, 16, 28, 878, 10751]",75571,Our War Game,ja,デジモンアドベンチャー ぼくらのウォーゲーム!,Spring break turns into a summer war when the ...,2.2520,/rY7XzmfQgwMYJXAZSIChU5FLP7y.jpg,2000-03-04,False,False,8.000,74
1638,85265,The Child,A woman returns to the Philippines after worki...,False,/g7rNNUQJsDM1tvoPWEdnvjKQK1N.jpg,[18],85265,The Child,tl,Anak,A woman returns to the Philippines after worki...,1.5468,/k7Q1jVPFhf1YmVdQO3dBHLfuSFE.jpg,2000-05-10,False,False,6.600,11
1298,230562,A Change of Heart,"Three siblings Danny, Art and Grace are now we...",False,/5yG6qiupfMzaCuRWWiIEwSUxxGs.jpg,"[10751, 18]",230562,A Change of Heart,tl,Tanging Yaman,"Three siblings Danny, Art and Grace are now we...",1.7700,/3UbZUv7qhjsSjkoIZMMuZHC3YgK.jpg,2000-11-08,False,False,7.000,3
120,1734,The Mummy Returns,"Rick and Evelyn O’Connell, along with their 8-...",False,/7s7WkAFPBsMTprYMbqbgKoppQsR.jpg,"[12, 28, 14]",1734,The Mummy Returns,en,The Mummy Returns,"Rick and Evelyn O’Connell, along with their 8-...",15.8746,/kdJsW7hcy1lrj7tdMPycTAQPAiR.jpg,2001-05-04,False,False,6.416,7891
72,808,Shrek,It ain't easy bein' green -- especially if you...,False,/w0eKUOEog2ImtktCHAMUZws8qif.jpg,"[16, 35, 14, 12, 10751]",808,Shrek,en,Shrek,It ain't easy bein' green -- especially if you...,33.3109,/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg,2001-05-18,False,False,7.779,19289